sonar.projectKey=shopflow
sonar.projectName=ShopFlow API
sonar.projectVersion=1.0

# Dossiers analysés
sonar.sources=app
sonar.tests=tests

# Langage
sonar.language=python
sonar.sourceEncoding=UTF-8

# Coverage (pytest-cov)
sonar.python.coverage.reportPaths=coverage.xml

# Rapport JUnit (tests)
sonar.python.xunit.reportPath=junit-report.xml

# Rapport pylint
sonar.python.pylint.reportPaths=pylint-report.txt

# Exclusions
sonar.exclusions=**/migrations/**,**/__init__.py,**/venv/**

# Attendre le Quality Gate (important pour Jenkins)
sonar.qualitygate.wait=true